### ISSUE TITLE
./docker_build.sh fails

### ISSUE THREAD

**Issue by bakingshoot** [secureworks/dcept#1]
Hi.

Attempting a new install under Debian, ./docker_build.sh fails here:

---

john-1.8.0-jumbo-1/src/pst_fmt_plug.c
john-1.8.0-jumbo-1/src/missing_getopt.c

gzip: stdin: unexpected end of file
john-1.8.0-jumbo-1/src/rules.c
john-1.8.0-jumbo-1/src/options.c
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
The command '/bin/sh -c mkdir /tmp/john && tar -xvf /tmp/john.tar.gz -C /tmp/john --strip-components=1' returned a non-zero code: 2
`

**Comment by bakingshoot** [comment]
Ran it again, got more data.

-----

Step 10 : RUN wget -O /tmp/john.tar.gz http://www.openwall.com/john/j/john-1.8.0-jumbo-1.tar.gz
 ---> Running in 33e88be15592
--2016-03-10 22:37:54--  http://www.openwall.com/john/j/john-1.8.0-jumbo-1.tar.gz
Resolving www.openwall.com (www.openwall.com)... 195.42.179.202
Connecting to www.openwall.com (www.openwall.com)|195.42.179.202|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: '/tmp/john.tar.gz'

     0K                                                        55.1M=0s

2016-03-10 22:37:54 (55.1 MB/s) - '/tmp/john.tar.gz' saved [939]

 ---> 63f01c623731
Removing intermediate container 33e88be15592
Step 11 : RUN mkdir /tmp/john && tar -xvf /tmp/john.tar.gz -C /tmp/john --strip-components=1
 ---> Running in 0a4eac798993

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c mkdir /tmp/john && tar -xvf /tmp/john.tar.gz -C /tmp/john --strip-components=1' returned a non-zero code: 2

**Comment by jamesscwx** [comment]
It appears as if wget got something else when it tried to download the John the Ripper tarball.

Below you'll notice the server response I receive from openwall.com contains the proper length and content- type, but yours is _Length: unspecified [text/html]_.

HTTP request sent, awaiting response... 200 OK
Length: 30786455 (29M) [application/x-tar]
Saving to: '/tmp/john.tar.gz'

Are you on a corporate network that might be proxying or blocking the download?
What happens when you run wget on the host?

_wget http://www.openwall.com/john/j/john-1.8.0-jumbo-1.tar.gz_

**Comment by bakingshoot** [comment]
I have to investigate this further.

-----

 wget http://www.openwall.com/john/j/john-1.8.0-jumbo-1.tar.gz
--2016-03-11 09:47:38--  http://www.openwall.com/john/j/john-1.8.0-jumbo-1.tar.gz
Resolving www.openwall.com (www.openwall.com)... 195.42.179.202
Connecting to www.openwall.com (www.openwall.com)|195.42.179.202|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30786455 (29M) [application/x-tar]
Saving to: ‘john-1.8.0-jumbo-1.tar.gz’

john-1.8.0-jumbo-1.tar.gz                          98%[==========================================================================================================>  ]  28.89M   945KB/s   in 29s

2016-03-11 09:48:10 (1.01 MB/s) - Read error at byte 30295120/30786455 (Connection reset by peer). Retrying.

--2016-03-11 09:48:11--  (try: 2)  http://www.openwall.com/john/j/john-1.8.0-jumbo-1.tar.gz
Connecting to www.openwall.com (www.openwall.com)|195.42.179.202|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘john-1.8.0-jumbo-1.tar.gz’

john-1.8.0-jumbo-1.tar.gz                             [ <=>                                                                                                         ]     939  --.-KB/s   in 0s

2016-03-11 09:48:11 (92.1 MB/s) - ‘john-1.8.0-jumbo-1.tar.gz’ saved [30295120]

root@rdep034:/home/agarrido/dcept/server# wget http://www.openwall.com/john/j/john-1.8.0-jumbo-1.tar.gz
--2016-03-11 09:48:21--  http://www.openwall.com/john/j/john-1.8.0-jumbo-1.tar.gz
Resolving www.openwall.com (www.openwall.com)... 195.42.179.202
Connecting to www.openwall.com (www.openwall.com)|195.42.179.202|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘john-1.8.0-jumbo-1.tar.gz.1’

john-1.8.0-jumbo-1.tar.gz.1                           [ <=>                                                                                                         ]     939  --.-KB/s   in 0s

2016-03-11 09:48:21 (78.8 MB/s) - ‘john-1.8.0-jumbo-1.tar.gz.1’ saved [939]

root@rdep034:/home/agarrido/dcept/server# gzip -d john-1.8.0-jumbo-1.tar.gz

gzip: john-1.8.0-jumbo-1.tar.gz: unexpected end of file

**Comment by jamesscwx** [comment]
It's definitely a network issue on your end.  As a workaround you could try downloading John the Ripper using an alternative method and then manually add it to the Docker container.

1.)  Either by proxy or on a different unfiltered network, successfully download john-1.8.0-jumbo-1.tar.gz
2.) Save john-1.8.0-jumbo-1.tar.gz to the server directory alongside the Dockerfile.
3.) Replace the “RUN wget" command at line 21 in the Dockerfile with the following:

```
    ADD ./john-1.8.0-jumbo-1.tar.gz /tmp/john.tar.gz
```

Now docker build will use the local tarball instead of downloading it.

**Comment by bakingshoot** [comment]
It's was a network issue on our end.  Stupid thing was sniffing everything looking for malware.
